name: build
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - run: apt update
      - run: apt -y --no-install-recommends install git ca-certificates curl
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: apt -y --no-install-recommends build-dep .
      - run: debuild -us -uc -b
