name: build & release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - run: apt update
      - name: install aux deps
        run: apt -y --no-install-recommends install git ca-certificates curl gnupg
      - name: add pgdg pkg repo
        run: >
          echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" >> /etc/apt/sources.list.d/pgdg.list &&
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg
      - run: apt update
      - name: clone repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install build-deps
        run: apt update && apt -y --no-install-recommends build-dep .
      - name: build
        run: debuild -us -uc -b
      - name: upload to pkg.yeti-switch.org. bullseye 1.12 main
        run: ci/deploy.sh bullseye 1.12 main ../*.deb
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
